import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';
import 'package:mpcb_bio_waste/HCF/add_bio_waste.dart';
import 'package:mpcb_bio_waste/Localization/app_localization.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../Global/AppDrawer.dart';
import '../Global/app_bar.dart';
import '../Global/app_button.dart';
import '../Global/app_dialog.dart';
import '../Global/constant.dart';
import '../Global/dataNotFound.dart';
import '../Global/images.dart';
import '../Global/size_config.dart';
import '../Global/url.dart';
import '../localization/provider.dart';
import '../network/network_aware.dart';
import '../network/network_status.dart';
import '../network/offline.dart';
import 'barcodeImage.dart';
import 'bio_waste_summary.dart';
import 'hcf_model.dart';

enum PrintType { barcode, qr }

class BioWasteDetailTableScreen extends StatefulWidget {
  final Map<String, dynamic> data;
  BioWasteDetailTableScreen(this.data, {super.key});

  @override
  State<BioWasteDetailTableScreen> createState() =>
      _BioWasteDetailTableScreenState();
}

class _BioWasteDetailTableScreenState extends State<BioWasteDetailTableScreen> {
  bool isLoadingbarcode = false;
  List<dynamic>? wasteList = [];
  bool isLoading = false;
  List<Map<String, dynamic>> selectedWasteEntries = [];
  bool isLoadingColor = false;
  Map<int, String> wasteColorLookup = {};
  Map<int, WasteGeneratedBy> wasteGeneratedByLookup = {};
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();

  List<HcfWasteModel> wasteData = [];
  Map<int, PrintType> printedRows = {}; // rowIndex → barcode / qr

  bool get isAllRowsPrinted =>
      printedRows.length == flattenedWasteEntries.length &&
      flattenedWasteEntries.isNotEmpty;

  @override
  void initState() {
    super.initState();
    GetCategoryList();
    GetWasteGeneratedByList();
    fetchBioWasteSummary();
  }

  Future<void> GetWasteGeneratedByList() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    var token = prefs.getString('Token');
    try {
      final response = await http.get(
        Uri.parse('$masterurl$WASTE_GENERATED_BY_LOOKUP'),
        headers: {
          'Content-Type': 'application/json; charset=UTF-8',
          'Accept': 'application/json ; charset=UTF-8',
          'Authorization': 'Bearer $token',
        },
      );
      if (response.statusCode == 200 || response.statusCode == 201) {
        final jsonResponse = jsonDecode(response.body);
        if (jsonResponse['status'] == 'success' && jsonResponse['data'] is List) {
          if (!mounted) return;
          setState(() {
            wasteGeneratedByLookup = {
              for (var item in jsonResponse['data'])
                item['lookupDetId']: WasteGeneratedBy.fromJson(item),
            };
          });
        }
      }
    } catch (e) {
      print('Error fetching waste generated by list: $e');
    }
  }

  Future<void> GetCategoryList() async {
    setState(() {
      isLoadingColor = true;
    });
    SharedPreferences prefs = await SharedPreferences.getInstance();
    var token = prefs.getString('Token');
    try {
      final headers = {
        'Content-Type': 'application/json; charset=UTF-8',
        'Accept': 'application/json ; charset=UTF-8',
        'Authorization': 'Bearer $token',
      };

      final url = Uri.parse('${baseurl}${CATEGORY_LOOKUP}');

      final response = await http.get(url, headers: headers);

      print(response.body);

      if (response.statusCode == 201) {
        final jsonResponse = jsonDecode(response.body);
        final List<dynamic> data = jsonResponse['data'];

        setState(() {
          wasteColorLookup = {
            for (var item in data) item['lookupDetId']: item['lookupDetDescEn'],
          };
        });
      } else {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(const SnackBar(content: Text('Authentication Error')));
        print("HTTP error: ${response.statusCode}");
      }
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Error fetching bio waste summary')),
      );
      print('Error fetching bio waste summary: $e');
    }

    setState(() {
      isLoadingColor = false;
    });
  }

  Color _getColor(String colorName) {
    switch (colorName.toLowerCase()) {
      case 'Y':
        return Colors.yellow;
      case 'R':
        return Colors.red;
      case 'B':
        return Colors.blue;
      case 'W':
        return Colors.white;
      default:
        return Colors.grey;
    }
  }

  List<Map<String, dynamic>> flattenedWasteEntries = [];

  Future<void> fetchBioWasteSummary() async {
    setState(() => isLoading = true);
    try {
      final int hcfWasteId = widget.data['hcfWasteId'];
      wasteList = widget.data['wasteList'] ?? [];

      flattenedWasteEntries.clear();
      selectedWasteEntries.clear();

      for (var waste in wasteList!) {
        final hcfWasteQntyId = waste["hcfWasteQntyId"];
        final categoryId = waste["lookupDetIdCategory"];
        final wasteGeneratedById = waste["lookupDetIdWasteGeneratedBy"];
        final wasteDetList = waste["wasteDetList"] ?? [];

        for (var det in wasteDetList) {
          final hcfWasteQntyDetId = det["hcfWasteQntyDetId"];
          final quantity = det["quantityBag"];

          // Store for table display
          flattenedWasteEntries.add({
            "hcfWasteId": hcfWasteId,
            "hcfWasteQntyId": hcfWasteQntyId,
            "hcfWasteQntyDetId": hcfWasteQntyDetId,
            "lookupDetIdCategory": categoryId,
            "lookupDetIdWasteGeneratedBy": wasteGeneratedById,
            "totalQuantityBagKg": quantity,
          });

          // Store for barcode printing
          selectedWasteEntries.add({
            "hcfWasteId": hcfWasteId,
            "hcfWasteQntyId": hcfWasteQntyId,
            "hcfWasteQntyDetId": hcfWasteQntyDetId,
          });
        }
      }

      print('Flattened entries: ${flattenedWasteEntries.length}');
    } catch (e) {
      print("Error: $e");
    }
    setState(() => isLoading = false);
  }

  final Map<String, Color> categoryColors = {
    'Yellow': Colors.yellow,
    'Red': Colors.red,
    'Blue': Colors.blue,
    'White': Colors.white,
  };

  Future<void> generateBarcode(Map<String, dynamic> selectedEntry) async {
    setState(() {
      isLoadingbarcode = true;
    });

    SharedPreferences prefs = await SharedPreferences.getInstance();
    var token = prefs.getString('Token');

    final body = {
      "hcfWasteId": selectedEntry["hcfWasteId"],
      "hcfWasteQntyDetId": selectedEntry["hcfWasteQntyDetId"],
      "hcfWasteQntyId": selectedEntry["hcfWasteQntyId"],
    };

    try {
      final headers = {
        'Content-Type': 'application/json; charset=UTF-8',
        'Accept': 'application/json ; charset=UTF-8',
        'Authorization': 'Bearer $token',
      };

      final response = await http.post(
        Uri.parse('${baseurl}${GENERATE_BARCODE}'),
        headers: headers,
        body: jsonEncode(body),
      );
      print(jsonEncode(body));

      if (response.statusCode == 200) {
        print(response.body);
        final Uint8List imageBytes = response.bodyBytes;
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_) => BarcodeImageScreen(imageBytes: imageBytes),
          ),
        );
      } else {
        print(response.statusCode);
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(const SnackBar(content: Text('Authentication Error')));
      }
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Error generating barcode')));
      print('Error: $e');
    }

    setState(() {
      isLoadingbarcode = false;
    });
  }

  Future<void> generateQR(Map<String, dynamic> selectedEntry) async {
    setState(() {
      isLoadingbarcode = true;
    });

    SharedPreferences prefs = await SharedPreferences.getInstance();
    var token = prefs.getString('Token');

    final body = {
      "hcfWasteId": selectedEntry["hcfWasteId"],
      "hcfWasteQntyDetId": selectedEntry["hcfWasteQntyDetId"],
      "hcfWasteQntyId": selectedEntry["hcfWasteQntyId"],
    };

    try {
      final headers = {
        'Content-Type': 'application/json; charset=UTF-8',
        'Accept': 'application/json ; charset=UTF-8',
        'Authorization': 'Bearer $token',
      };

      final response = await http.post(
        Uri.parse('${baseurl}${GENERATE_QRCODE}'),
        headers: headers,
        body: jsonEncode(body),
      );
      print(jsonEncode(body));

      if (response.statusCode == 200) {
        print(response.body);
        final Uint8List imageBytes = response.bodyBytes;
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (_) => BarcodeImageScreen(imageBytes: imageBytes),
          ),
        );
      } else {
        print(response.statusCode);
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(const SnackBar(content: Text('Authentication Error')));
      }
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Error generating barcode')));
      print('Error: $e');
    }

    setState(() {
      isLoadingbarcode = false;
    });
  }

  Future<void> MultiplePrint(result) async {
    // Convert selected entries to model
    wasteData =
        selectedWasteEntries
            .map((item) {
              return HcfWasteModel(
                hcfWasteId: item['hcfWasteId'],
                hcfWasteQntyDetId: item['hcfWasteQntyDetId'],
                hcfWasteQntyId: item['hcfWasteQntyId'],
              );
            })
            .where(
              (e) => e.hcfWasteQntyDetId != null && e.hcfWasteQntyId != null,
            )
            .toList();

    debugPrint("✅ Waste Data Count: ${wasteData.length}");
    debugPrint(
      "📦 Waste Data Body: ${jsonEncode(wasteData.map((e) => e.toJson()).toList())}",
    );

    if (wasteData.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('No valid waste entries found')),
      );
      return;
    }

    final body = wasteData.map((e) => e.toJson()).toList();

    SharedPreferences prefs = await SharedPreferences.getInstance();
    var token = prefs.getString('Token');
    Map<String, dynamic> user = jsonDecode(prefs.getString('user')!);

    try {
      final headers = {
        'Content-Type': 'application/json; charset=UTF-8',
        'Accept': 'application/json ; charset=UTF-8',
        'Authorization': 'Bearer $token',
      };
      final response;
      if (result == PrintType.barcode) {
        response = await http.post(
          Uri.parse('$baseurl$MULTIPLE_BARCODE'),
          headers: headers,
          body: jsonEncode(body),
        );
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(const SnackBar(content: Text('Printing Barcode')));
      } else {
        response = await http.post(
          Uri.parse('$baseurl$MULTIPLE_QR'),
          headers: headers,
          body: jsonEncode(body),
        );
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(const SnackBar(content: Text('Printing QR')));
      }

      debugPrint("📤 Sent Body: ${jsonEncode(body)}");
      debugPrint("📥 Response Code: ${response.statusCode}");
      debugPrint("📥 Response Body: ${response.body}");

      if (response.statusCode == 200) {
        // Check if API returns multiple images or just one
        try {
          // final decoded = jsonDecode(response.body);
          // if (decoded is List) {
          //   // If multiple barcodes
          //   Navigator.push(
          //     context,
          //     MaterialPageRoute(
          //       builder: (_) => MultipleBarcodeScreen(barcodes: decoded),
          //     ),
          //   );
          // } else {
          // If single barcode image
          final Uint8List imageBytes = response.bodyBytes;
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (_) => BarcodeImageScreen(imageBytes: imageBytes),
            ),
          );
          //}
        } catch (_) {
          // Fallback to single image
          final Uint8List imageBytes = response.bodyBytes;
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (_) => BarcodeImageScreen(imageBytes: imageBytes),
            ),
          );
        }

        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Data submitted successfully')),
        );
      } else {
        debugPrint('❌ Error: ${response.body}');
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(const SnackBar(content: Text('Submission failed')));
      }
    } catch (e) {
      debugPrint('❌ Error fetching barcodes: $e');
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Error fetching barcodes')));
    }
  }

  Future<void> sendtoCBWTF(t) async {
    setState(() {
      isLoadingbarcode = true;
    });

    SharedPreferences prefs = await SharedPreferences.getInstance();
    var token = prefs.getString('Token');
    wasteData =
        selectedWasteEntries
            .map((item) {
              return HcfWasteModel(
                hcfWasteId: item['hcfWasteId'],
                hcfWasteQntyDetId: item['hcfWasteQntyDetId'],
                hcfWasteQntyId: item['hcfWasteQntyId'],
              );
            })
            .where(
              (e) => e.hcfWasteQntyDetId != null && e.hcfWasteQntyId != null,
            )
            .toList();
    final int? wasteId =
        wasteData.isNotEmpty ? wasteData.first.hcfWasteId : null;

    if (wasteId == null) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Waste ID not found')));
      setState(() => isLoadingbarcode = false);
      return;
    }

    try {
      final headers = {
        'Content-Type': 'application/json; charset=UTF-8',
        'Accept': 'application/json ; charset=UTF-8',
        'Authorization': 'Bearer $token',
      };

      final response = await http.post(
        Uri.parse('${baseurl}${SEND_TO_CBWTF}$wasteId'),
        headers: headers,
      );

      if (response.statusCode == 200) {
        print(response.body);
        showDialog(
          context: context,
          barrierDismissible: false,
          builder:
              (_) => SuccessDialog(
                buttonText: t.translate('ok'),
                message:  t.translate('cbwtf_data_sent'),
                onOk: () {
                  Navigator.pop(context);

                  Navigator.pushReplacement(
                    context,
                    MaterialPageRoute(
                      builder: (context) => AddBioWasteDataTab(),
                    ),
                  );
                },
              ),
        );
      } else {
        print(response.statusCode);
      }
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Error Sending Data')));
      print('Error: $e');
    }

    setState(() {
      isLoadingbarcode = false;
    });
  }

  void showConfirmation(BuildContext context,t) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (BuildContext context) {
        return AlertDialog(
          // title: Image.asset(success),
          content: Text(
            t.translate('are_you_sure_you_want_to_go_back'),
            style: TextStyle(fontWeight: FontWeight.bold),
            textAlign: TextAlign.center,
          ),
          actions: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: [
                SizedBox(
                  width: 100,
                  child: AppButton(
                    text:  t.translate('no'),
                    onPressed: () {
                      Navigator.pop(context);
                    },
                    color: Colors.grey.shade500,
                    padding: EdgeInsetsGeometry.all(10),
                  ),
                ),
                SizedBox(
                  width: 100,
                  child: AppButton(
                    text:  t.translate('yes'),
                    onPressed: () {
                      Navigator.pop(context);
                      Navigator.pop(context);
                      Navigator.pushReplacement(
                        context,
                        MaterialPageRoute(builder: (_) => AddBioWasteDataTab()),
                      );
                    },
                    color: Colors.deepOrange,
                    padding: EdgeInsetsGeometry.all(10),
                  ),
                ),
              ],
            ),
          ],
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    SizeConfig().init(context);
    final t = AppLocalizations.of(context);
    final langProvider = context.watch<LanguageProvider>();

    return StreamProvider<NetworkStatus>(
      create:
          (context) => NetworkStatusService().networkStatusController.stream,
      initialData: NetworkStatus.Online,
      child: NetworkAwareWidget(
        onlineChild: Scaffold(
          key: _scaffoldKey,
          drawer: AppDrawer(),
          body: Stack(
            children: [
              /// Custom Gradient AppBar
              mAppBar(
                scTitle: t.translate('hcf_data'),
                centerTile: false,
                onLeadingIconClick: () {
                  showConfirmation(context,t);
                },
                showLeading: true,
                showActions: true,
                actions: [
                  IconButton(
                    onPressed: () async {
                      final PrintType? result = await showPrintDialog(context,t);

                      if (result == null) return; // user cancelled

                      MultiplePrint(result);
                      setState(() {
                        for (int i = 0; i < flattenedWasteEntries.length; i++) {
                          printedRows[i] = result;
                        }
                      });

                      //   sendWasteData();
                      //  showPrintDialog(context);
                    },
                    icon: Icon(Icons.print),
                  ),
                ],
              ),

              /// Body with tabs
              Positioned.fill(
                top: responsiveHeight(110),
                bottom: responsiveHeight(
                  0,
                ), // offset to appear below custom app bar
                child: Container(
                  padding: const EdgeInsets.all(15),

                  decoration: BoxDecoration(
                    color: kWhiteColor,
                    borderRadius: const BorderRadius.only(
                      topRight: Radius.circular(40),
                      topLeft: Radius.circular(40),
                    ),
                  ),
                  child:
                      isLoading || isLoadingColor
                          ? const Center(child: CircularProgressIndicator())
                          : wasteList!.isEmpty || wasteList == null
                          ? Datanotfound()
                          : Column(
                            children: [
                              const SizedBox(height: 4),
                              Expanded(
                                child: Table(
                                  border: TableBorder.all(
                                    color: Colors.grey.shade300,
                                    borderRadius: const BorderRadius.all(
                                      Radius.circular(10),
                                    ),
                                  ),
                                  columnWidths: const {
                                    0: FlexColumnWidth(0.9),
                                    1: FlexColumnWidth(2.1),
                                    2: FlexColumnWidth(2.3),
                                    3: FlexColumnWidth(1.7),
                                    4: FlexColumnWidth(1.5),
                                    5: FlexColumnWidth(1.5),
                                  },
                                  children: [
                                    TableRow(
                                      decoration: const BoxDecoration(
                                        borderRadius: BorderRadius.only(
                                          topRight: Radius.circular(10),
                                          topLeft: Radius.circular(10),
                                        ),
                                        gradient: LinearGradient(
                                          colors: [
                                            Color(0xFF00B4DB),
                                            Color(0xFF0099CC),
                                          ],
                                        ),
                                      ),
                                      children:  [
                                        Padding(
                                          padding: EdgeInsets.all(8),
                                          child: Text(
                                            t.translate('bag_no'),
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontWeight: FontWeight.bold,
                                              fontSize: 10,
                                            ),
                                          ),
                                        ),
                                        Padding(
                                          padding: EdgeInsets.all(8),
                                          child: Text(
                                            t.translate('category'),
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontWeight: FontWeight.bold,
                                              fontSize: 10,
                                            ),
                                          ),
                                        ),
                                        Padding(
                                          padding: const EdgeInsets.all(4),
                                          child: Text(
                                            t.translate('waste_generated_by'),
                                            style: const TextStyle(
                                              color: Colors.white,
                                              fontWeight: FontWeight.bold,
                                              fontSize: 9,
                                            ),
                                          ),
                                        ),
                                        Padding(
                                          padding: EdgeInsets.all(8),
                                          child: Text(
                                            t.translate('weight'),
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontWeight: FontWeight.bold,
                                              fontSize: 10,
                                            ),
                                          ),
                                        ),
                                        // Padding(
                                        //   padding: EdgeInsets.all(8),
                                        //   child: Text(
                                        //     "No. of Bags",
                                        //     style: TextStyle(
                                        //       color: Colors.white,
                                        //       fontWeight: FontWeight.bold,
                                        //     ),
                                        //   ),
                                        // ),
                                        Padding(
                                          padding: const EdgeInsets.symmetric(
                                            vertical: 8,
                                            horizontal: 2,
                                          ),
                                          child: Text(
                                            t.translate('print_barcode'),
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontWeight: FontWeight.bold,
                                              fontSize: 10,
                                            ),
                                          ),
                                        ),
                                        Padding(
                                          padding: const EdgeInsets.symmetric(
                                            vertical: 8,
                                            horizontal: 2,
                                          ),
                                          child: Text(
                                            t.translate('print_qr'),
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontWeight: FontWeight.bold,
                                              fontSize: 10,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                    for (
                                      int i = 0;
                                      i < flattenedWasteEntries.length;
                                      i++
                                    )
                                      TableRow(
                                        children: [
                                          Padding(
                                            padding: const EdgeInsets.all(4),
                                            child: Text("${i + 1}"),
                                          ),
                                          Padding(
                                            padding: const EdgeInsets.all(4),
                                            child: Row(
                                              children: [
                                                Container(
                                                  width: 14,
                                                  height: 14,
                                                  color:
                                                      categoryColors[wasteColorLookup[flattenedWasteEntries[i]['lookupDetIdCategory']]] ??
                                                      Colors.grey,
                                                ),
                                                const SizedBox(width: 4),
                                                Flexible(
                                                  child: Text(
                                                    wasteColorLookup[flattenedWasteEntries[i]['lookupDetIdCategory']] ??
                                                        '',
                                                    style: const TextStyle(
                                                      fontSize: 12,
                                                    ),
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                          Padding(
                                            padding: const EdgeInsets.all(4),
                                            child: Text(
                                              wasteGeneratedByLookup[flattenedWasteEntries[i]['lookupDetIdWasteGeneratedBy']]
                                                      ?.nameFor(
                                                        langProvider
                                                            .locale
                                                            .languageCode,
                                                      ) ??
                                                  '-',
                                              textAlign: TextAlign.center,
                                              style: const TextStyle(
                                                fontSize: 11,
                                              ),
                                            ),
                                          ),
                                          Padding(
                                            padding: const EdgeInsets.all(8),
                                            child: TextFormField(
                                              initialValue:
                                                  flattenedWasteEntries[i]['totalQuantityBagKg']
                                                      .toString(),
                                              onChanged: (val) {
                                                flattenedWasteEntries[i]['totalQuantityBagKg'] =
                                                    double.tryParse(val) ?? 0;
                                              },
                                            ),
                                          ),
                                          IconButton(
                                            icon: Icon(
                                              Icons.print,
                                              color:
                                                  printedRows[i] ==
                                                          PrintType.barcode
                                                      ? Colors.green
                                                      : Colors.grey,
                                            ),
                                            onPressed:
                                                isLoadingbarcode
                                                    ? null
                                                    : () async {
                                                      await generateBarcode(
                                                        selectedWasteEntries[i],
                                                      );
                                                      setState(() {
                                                        printedRows[i] =
                                                            PrintType.barcode;
                                                      });
                                                    },
                                          ),
                                          IconButton(
                                            icon: Icon(
                                              Icons.print,
                                              color:
                                                  printedRows[i] == PrintType.qr
                                                      ? Colors.green
                                                      : Colors.grey,
                                            ),
                                            onPressed:
                                                isLoadingbarcode
                                                    ? null
                                                    : () async {
                                                      await generateQR(
                                                        selectedWasteEntries[i],
                                                      );
                                                      setState(() {
                                                        printedRows[i] =
                                                            PrintType.qr;
                                                      });
                                                    },
                                          ),
                                        ],
                                      ),
                                  ],
                                ),
                              ),
                              if (isAllRowsPrinted) ...[
                                const SizedBox(height: 16),
                                SizedBox(
                                  width: 170,
                                  child: AppButton(
                                    text: t.translate('submit'),
                                    color: Colors.deepOrange,
                                    padding: const EdgeInsets.all(14),
                                    onPressed: () {
                                      // 🔥 Final submit API
                                      debugPrint(
                                        "All rows printed. Submitting...",
                                      );

                                      sendtoCBWTF(t);
                                    },
                                  ),
                                ),
                                const SizedBox(height: 16),
                              ],
                            ],
                          ),
                ),
              ),
            ],
          ),
        ),
        offlineChild: Offline(),
      ),
    );
  }

  Future<PrintType?> showPrintDialog(BuildContext context,t) {
    PrintType selectedType = PrintType.barcode;

    return showDialog<PrintType>(
      context: context,
      barrierDismissible: false,
      builder: (context) {
        return StatefulBuilder(
          builder: (context, setState) {
            return Dialog(
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(20),
              ),
              child: Padding(
                padding: const EdgeInsets.all(20),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    /// Printer Icon
                    Image.asset('assets/images/printer.png', height: 80),

                    const SizedBox(height: 10),

                    /// Title
                     Text(
                      t.translate('print_question'),
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w600,
                      ),
                    ),

                    const SizedBox(height: 20),

                    /// Radio Buttons
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Radio<PrintType>(
                          value: PrintType.barcode,
                          groupValue: selectedType,
                          onChanged: (val) {
                            setState(() => selectedType = val!);
                          },
                        ),
                        Text( t.translate('barcode')),

                        const SizedBox(width: 20),

                        Radio<PrintType>(
                          value: PrintType.qr,
                          groupValue: selectedType,
                          onChanged: (val) {
                            setState(() => selectedType = val!);
                          },
                        ),
                        Text( t.translate('qr')),
                      ],
                    ),

                    const SizedBox(height: 24),

                    /// Buttons
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        SizedBox(
                          width: 110,
                          child: AppButton(
                            text:  t.translate('cancel'),
                            color: Colors.grey.shade400,
                            padding: const EdgeInsets.all(10),
                            onPressed: () {
                              Navigator.pop(context, null); // ❗ return null
                            },
                          ),
                        ),

                        SizedBox(
                          width: 110,
                          child: AppButton(
                            text:  t.translate('print'),
                            color: Colors.deepOrange,
                            padding: const EdgeInsets.all(10),
                            onPressed: () {
                              Navigator.pop(
                                context,
                                selectedType,
                              ); // ✅ return value
                            },
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            );
          },
        );
      },
    );
  }
}
