// bio_waste_mapper.dart

class BioWasteMapper {
  static Map<String, dynamic> buildPayload({
    required List<Map<String, dynamic>> tableData,
    required int hcfId,
    required String hcfCode,
    required String wasteQntyDate,
    required int userId,
    required String createdDate,
    required String updatedDate,
    required String macId,
    required String ipAddress,
  }) {
    final wasteList = _transformTableDataToWasteList(
      tableData: tableData,
      userId: userId,
      createdDate: createdDate,
      updatedDate: updatedDate,
      macId: macId,
      ipAddress: ipAddress,
    );

    final totalQty = tableData.fold<double>(
        0, (sum, row) => sum + (double.tryParse(row['quantity'].toString()) ?? 0));

    return {
      "hcfWasteId": null,
      "hcfId": hcfId,
      "hcfCode": hcfCode,
      "wasteQntyDate": wasteQntyDate,
      "totalNoOfBags": tableData.length,
      "totalQuantityBagKg": totalQty,
      "userId": userId,
      "status": 1,
      "createdBy": userId,
      "createdDate": createdDate,
      "updatedBy": userId,
      "updatedDate": updatedDate,
      "macId": macId,
      "ipAddress": ipAddress,
      "deviceFrom": "M",
      "wasteList": wasteList,
    };
  }

  static List<Map<String, dynamic>> _transformTableDataToWasteList({
    required List<Map<String, dynamic>> tableData,
    required int userId,
    required String createdDate,
    required String updatedDate,
    required String macId,
    required String ipAddress,
  }) {
    // One wasteList entry per (category, waste generated by) pair.
    final Map<String, List<Map<String, dynamic>>> grouped = {};

    for (var entry in tableData) {
      final key = '${entry['id']}_${entry['wasteGeneratedById']}';
      grouped.putIfAbsent(key, () => []).add(entry);
    }

    return grouped.values.map((groupRows) {

      double totalQuantity = 0;
      int bagCounter = 1;

      final wasteDetList = groupRows.map((row) {
        final double qty = double.tryParse(row['quantity'].toString()) ?? 0;
        totalQuantity += qty;
        print('roe');
        print(row['category'].toString().substring(0,1));

        return {
          "hcfWasteQntyDetId": null,
          "bagNo": bagCounter++,
          "quantityBag": qty,
          "status": 1,
          "createdBy": userId,
          "createdDate": createdDate,
          "updatedBy": userId,
          "updatedDate": updatedDate,
          "macId": macId,
          "ipAddress": ipAddress,
          "deviceFrom": "M",
          "colorType": row['category'].toString().substring(0,1), // must be present in tableData
        };
      }).toList();

      return {
        "hcfWasteQntyId": null,
        "lookupDetIdCategory": groupRows.first['id'],
        "noOfBags": groupRows.length,
        "totalQuantityBagKg": totalQuantity,
        "lookupDetIdWasteGeneratedBy": groupRows.first['wasteGeneratedById'],
        "status": 1,
        "createdBy": userId,
        "createdDate": createdDate,
        "updatedBy": userId,
        "updatedDate": updatedDate,
        "macId": macId,
        "ipAddress": ipAddress,
        "deviceFrom": "M",
        "wasteDetList": wasteDetList,
      };
    }).toList();
  }
}

class WasteGeneratedBy {
  final int id;
  final String nameEn;
  final String nameRg;

  WasteGeneratedBy({
    required this.id,
    required this.nameEn,
    required this.nameRg,
  });

  factory WasteGeneratedBy.fromJson(Map<String, dynamic> json) {
    final en = (json['lookupDetDescEn'] ?? '').toString();
    final rg = (json['lookupDetDescRg'] ?? '').toString();
    return WasteGeneratedBy(
      id: json['lookupDetId'],
      nameEn: en,
      nameRg: rg.isEmpty ? en : rg,
    );
  }

  String nameFor(String languageCode) => languageCode == 'mr' ? nameRg : nameEn;
}

class ColorCategory {
  final int id;
  final String name;
  final String code;

  ColorCategory({
    required this.id,
    required this.name,
    required this.code,
  });

  factory ColorCategory.fromJson(Map<String, dynamic> json) {
    return ColorCategory(
      id: json['lookupDetId'],
      name: json['lookupDetDescEn'],
      code: json['lookupDetValue'],
    );
  }
}
